<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20181021012527 extends AbstractMigration
{
    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE MGMT_USER_FONCTION DROP FOREIGN KEY fk_MGMT_USER_FONCTION_MGMT_FONCTION1');
        $this->addSql('ALTER TABLE MGMT_FONCTION DROP FOREIGN KEY fk_MGMT_FONCTION_MGMT_POLE1');
        $this->addSql('ALTER TABLE MGMT_PROJET_LOT DROP FOREIGN KEY fk_MGMT_PROJET_LOT_MGMT_PROJET1');
        $this->addSql('ALTER TABLE MGMT_PROJET_LOT_EQUIPE DROP FOREIGN KEY fk_MGMT_PROJET_LOT_EQUIPE_MGMT_PROJET_LOT1');
        $this->addSql('ALTER TABLE MGMT_PROJET_LOT_TACHE DROP FOREIGN KEY fk_MGMT_PROJET_LOT_TACHE_MGMT_PROJET_LOT1');
        $this->addSql('ALTER TABLE MGMT_PROJET_LOT DROP FOREIGN KEY fk_MGMT_PROJET_LOT_MGMT_PROJET_LOT_STATUT1');
        $this->addSql('ALTER TABLE MGMT_PROJET_LOT_TACHE DROP FOREIGN KEY fk_MGMT_PROJET_LOT_TACHE_MGMT_PROJET_LOT_TACHE1');
        $this->addSql('ALTER TABLE MGMT_PROJET_LOT_TACHE DROP FOREIGN KEY fk_MGMT_PROJET_LOT_TACHE_MGMT_PROJET_LOT_TACHE_STATUT1');
        $this->addSql('ALTER TABLE TZ_SEKOLIKO_EDT DROP FOREIGN KEY fk_TZ_SEKOLIKO_EDT_TZ-SEKOLIKO-MATIERE1');
        $this->addSql('ALTER TABLE TZ_SEKOLIKO_NOTE DROP FOREIGN KEY fk_TZ_SEKOLIKO_NOTE_TZ-SEKOLIKO-MATIERE1');
        $this->addSql('ALTER TABLE TZ-SEKOLIKO-MATIERE DROP FOREIGN KEY fk_TZ-SEKOLIKO-MATIERE_TZ-SEKOLIKO-PROF1');
        $this->addSql('ALTER TABLE TZ_SEKOLIKO_EDT DROP FOREIGN KEY fk_TZ_SEKOLIKO_EDT_TZ-SEKOLIKO-PROF1');
        $this->addSql('ALTER TABLE TZ_SEKOLIKO_PAIEMENT DROP FOREIGN KEY fk_TZ_SEKOLIKO_PAYEMENT_TZ-SEKOLIKO-PROF1');
        $this->addSql('ALTER TABLE TZ_SEKOLIKO_PAIEMENT DROP FOREIGN KEY fk_TZ_SEKOLIKO_PAYEMENT_TZ_SEKOLIKO_ADMIN1');
        $this->addSql('ALTER TABLE TZ_SEKOLIKO_ETUDIANT DROP FOREIGN KEY fk_TZ_SEKOLIKO_ETUDIANT_TZ_SEKOLIKO_CLASSE1');
        $this->addSql('ALTER TABLE MGMT_PROJET_LOT_EQUIPE DROP FOREIGN KEY fk_MGMT_PROJET_LOT_EQUIPE_MGMT_USER1');
        $this->addSql('ALTER TABLE MGMT_PROJET_LOT_TACHE DROP FOREIGN KEY fk_MGMT_PROJET_LOT_TACHE_MGMT_USER1');
        $this->addSql('ALTER TABLE MGMT_USER_FONCTION DROP FOREIGN KEY fk_MGMT_USER_FONCTION_MGMT_USER1');
        $this->addSql('ALTER TABLE TZ_SEKOLIKO_SESSION DROP FOREIGN KEY fk_TZ_SEKOLY_SESSION_TZ_SEKOLIKO_ETABLISSEMENT1');
        $this->addSql('ALTER TABLE TZ_SEKOLIKO_NOTE DROP FOREIGN KEY fk_TZ_SEKOLIKO_NOTE_TZ_SEKOLIKO_ETUDIANT1');
        $this->addSql('ALTER TABLE TZ_SEKOLIKO_ETUDIANT DROP FOREIGN KEY fk_TZ_SEKOLIKO_ETUDIANT_TZ_SEKOLIKO_PAYEMENT1');
        $this->addSql('ALTER TABLE TZ-SEKOLIKO-PROF DROP FOREIGN KEY fk_TZ-SEKOLIKO-PROF_TZ_SEKOLIKO_SESSION1');
        $this->addSql('ALTER TABLE TZ_SEKOLIKO_ADMIN DROP FOREIGN KEY fk_TZ_SEKOLIKO_ADMIN_TZ_SEKOLIKO_SESSION1');
        $this->addSql('ALTER TABLE TZ_SEKOLIKO_CLASSE DROP FOREIGN KEY fk_TZ_SEKOLIKO_CLASSE_TZ_SEKOLIKO_SESSION1');
        $this->addSql('CREATE TABLE sekoliko_horaire (id INT AUTO_INCREMENT NOT NULL, hr_date_debut_saison DATETIME DEFAULT NULL, hr_date_fin_saison DATETIME DEFAULT NULL, hr_debut TIME DEFAULT NULL, hr_fin TIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sekoliko_jour_ferie (id INT AUTO_INCREMENT NOT NULL, jr_fer_nom VARCHAR(45) DEFAULT NULL, jr_fer_date DATE DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sekoliko_role (id INT AUTO_INCREMENT NOT NULL, rl_name VARCHAR(45) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sekoliko_user (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(180) NOT NULL, username_canonical VARCHAR(180) NOT NULL, email VARCHAR(180) NOT NULL, email_canonical VARCHAR(180) NOT NULL, enabled TINYINT(1) NOT NULL, salt VARCHAR(255) DEFAULT NULL, password VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, confirmation_token VARCHAR(180) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', usr_firstname VARCHAR(255) DEFAULT NULL, usr_lastname VARCHAR(255) DEFAULT NULL, usr_address VARCHAR(255) DEFAULT NULL, usr_date_create DATETIME DEFAULT NULL, usr_date_update DATETIME DEFAULT NULL, usr_phone VARCHAR(45) DEFAULT NULL, usr_photo VARCHAR(255) DEFAULT NULL, usr_raison_sociale VARCHAR(255) DEFAULT NULL, usr_color VARCHAR(10) DEFAULT \'#ff00ff\' NOT NULL, UNIQUE INDEX username_canonical_UNIQUE (username_canonical), UNIQUE INDEX email_canonical_UNIQUE (email_canonical), UNIQUE INDEX confirmation_token_UNIQUE (confirmation_token), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('DROP TABLE MGMT_FONCTION');
        $this->addSql('DROP TABLE MGMT_POLE');
        $this->addSql('DROP TABLE MGMT_PROJET');
        $this->addSql('DROP TABLE MGMT_PROJET_LOT');
        $this->addSql('DROP TABLE MGMT_PROJET_LOT_EQUIPE');
        $this->addSql('DROP TABLE MGMT_PROJET_LOT_STATUT');
        $this->addSql('DROP TABLE MGMT_PROJET_LOT_TACHE');
        $this->addSql('DROP TABLE MGMT_PROJET_LOT_TACHE_STATUT');
        $this->addSql('DROP TABLE MGMT_USER_FONCTION');
        $this->addSql('DROP TABLE TZ-SEKOLIKO-MATIERE');
        $this->addSql('DROP TABLE TZ-SEKOLIKO-PROF');
        $this->addSql('DROP TABLE TZ_SEKOLIKO_ADMIN');
        $this->addSql('DROP TABLE TZ_SEKOLIKO_CLASSE');
        $this->addSql('DROP TABLE TZ_SEKOLIKO_ETABLISSEMENT');
        $this->addSql('DROP TABLE TZ_SEKOLIKO_ETUDIANT');
        $this->addSql('DROP TABLE TZ_SEKOLIKO_NOTE');
        $this->addSql('DROP TABLE TZ_SEKOLIKO_PAIEMENT');
        $this->addSql('DROP TABLE TZ_SEKOLIKO_SESSION');
        $this->addSql('ALTER TABLE TZ_SEKOLIKO_SALLE CHANGE id id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE TZ_SEKOLIKO_EDT DROP FOREIGN KEY fk_TZ_SEKOLIKO_EDT_TZ_SEKOLIKO_SALLE1');
        $this->addSql('DROP INDEX fk_TZ_SEKOLIKO_EDT_TZ-SEKOLIKO-MATIERE1_idx ON TZ_SEKOLIKO_EDT');
        $this->addSql('DROP INDEX fk_TZ_SEKOLIKO_EDT_TZ-SEKOLIKO-PROF1_idx ON TZ_SEKOLIKO_EDT');
        $this->addSql('DROP INDEX fk_TZ_SEKOLIKO_EDT_TZ_SEKOLIKO_SALLE1_idx ON TZ_SEKOLIKO_EDT');
        $this->addSql('ALTER TABLE TZ_SEKOLIKO_EDT DROP TZ-SEKOLIKO-MATIERE_id, DROP TZ-SEKOLIKO-PROF_id, DROP TZ_SEKOLIKO_SALLE_id, CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE tz_sekoliko_edt_heure_debut tz_sekoliko_edt_heure_debut DATETIME DEFAULT NULL, CHANGE tz_sekoliko_edt_heure_fin tz_sekoliko_edt_heure_fin DATETIME DEFAULT NULL');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE MGMT_FONCTION (id INT AUTO_INCREMENT NOT NULL, fct_libelle VARCHAR(255) NOT NULL COLLATE utf8_general_ci, fct_desc TEXT DEFAULT NULL COLLATE utf8_general_ci, MGMT_POLE_id INT NOT NULL, INDEX fk_MGMT_FONCTION_MGMT_POLE1_idx (MGMT_POLE_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE MGMT_POLE (id INT NOT NULL, pl_libelle VARCHAR(255) NOT NULL COLLATE utf8_general_ci, pl_desc TEXT DEFAULT NULL COLLATE utf8_general_ci, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE MGMT_PROJET (id INT AUTO_INCREMENT NOT NULL, prj_nom VARCHAR(255) NOT NULL COLLATE utf8_general_ci, prj_abrv VARCHAR(10) DEFAULT NULL COLLATE utf8_general_ci, prj_date_obtention DATETIME DEFAULT NULL, prj_date_ajout DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, MGMT_PROJET_TYPE_id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE MGMT_PROJET_LOT (id INT AUTO_INCREMENT NOT NULL, prj_lot_nom VARCHAR(255) NOT NULL COLLATE utf8_general_ci, prj_lot_desc TEXT DEFAULT NULL COLLATE utf8_general_ci, prj_lot_date_ajout DATETIME NOT NULL, prj_lot_date_debut DATETIME DEFAULT NULL, prj_lot_date_prevu_livraison DATETIME DEFAULT NULL, prj_lot_date_livraison DATETIME DEFAULT NULL, MGMT_PROJET_LOT_STATUT_id INT NOT NULL, MGMT_PROJET_id INT NOT NULL, INDEX fk_MGMT_PROJET_LOT_MGMT_PROJET_LOT_STATUT1_idx (MGMT_PROJET_LOT_STATUT_id), INDEX fk_MGMT_PROJET_LOT_MGMT_PROJET1_idx (MGMT_PROJET_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE MGMT_PROJET_LOT_EQUIPE (id INT AUTO_INCREMENT NOT NULL, prj_lot_eqp_nom VARCHAR(100) NOT NULL COLLATE utf8_general_ci, prj_lot_eqp_date_debut DATETIME DEFAULT NULL, prj_lot_eqp_date_fin DATETIME DEFAULT NULL, prj_lot_eqp_is_responsable TINYINT(1) DEFAULT NULL, MGMT_USER_id INT NOT NULL, MGMT_PROJET_LOT_id INT NOT NULL, INDEX fk_MGMT_PROJET_LOT_EQUIPE_MGMT_USER1_idx (MGMT_USER_id), INDEX fk_MGMT_PROJET_LOT_EQUIPE_MGMT_PROJET_LOT1_idx (MGMT_PROJET_LOT_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE MGMT_PROJET_LOT_STATUT (id INT AUTO_INCREMENT NOT NULL, prj_lot_st_libelle VARCHAR(50) NOT NULL COLLATE utf8_general_ci, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE MGMT_PROJET_LOT_TACHE (id INT AUTO_INCREMENT NOT NULL, prj_lot_tch_libelle VARCHAR(255) NOT NULL COLLATE utf8_general_ci, prj_lot_tch_date_attribution DATETIME DEFAULT NULL, prj_lot_tch_date_debut DATETIME DEFAULT NULL, prj_lot_tch_date_fin DATETIME DEFAULT NULL, prj_lot_tch_estimation_pers DOUBLE PRECISION DEFAULT NULL COMMENT \'En heure\', prj_lot_tch_estimation_resp DOUBLE PRECISION DEFAULT NULL, prj_lot_tch_desc TEXT DEFAULT NULL COLLATE utf8_general_ci, MGMT_USER_id INT NOT NULL, MGMT_PROJET_LOT_id INT NOT NULL, MGMT_PROJET_LOT_TACHE_STATUT_id INT NOT NULL, MGMT_PROJET_LOT_TACHE_id INT DEFAULT NULL, INDEX fk_MGMT_PROJET_LOT_TACHE_MGMT_USER1_idx (MGMT_USER_id), INDEX fk_MGMT_PROJET_LOT_TACHE_MGMT_PROJET_LOT1_idx (MGMT_PROJET_LOT_id), INDEX fk_MGMT_PROJET_LOT_TACHE_MGMT_PROJET_LOT_TACHE_STATUT1_idx (MGMT_PROJET_LOT_TACHE_STATUT_id), INDEX fk_MGMT_PROJET_LOT_TACHE_MGMT_PROJET_LOT_TACHE1_idx (MGMT_PROJET_LOT_TACHE_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE MGMT_PROJET_LOT_TACHE_STATUT (id INT AUTO_INCREMENT NOT NULL, prj_lot_tch_st_libelle VARCHAR(25) DEFAULT NULL COLLATE utf8_general_ci, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE MGMT_USER_FONCTION (id INT AUTO_INCREMENT NOT NULL, usr_fct_date_debut DATETIME DEFAULT NULL, usr_fct_date_fin DATETIME DEFAULT NULL, MGMT_USER_id INT NOT NULL COMMENT \'cascade\', MGMT_FONCTION_id INT NOT NULL, INDEX fk_MGMT_USER_FONCTION_MGMT_USER1_idx (MGMT_USER_id), INDEX fk_MGMT_USER_FONCTION_MGMT_FONCTION1_idx (MGMT_FONCTION_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE TZ-SEKOLIKO-MATIERE (id INT NOT NULL, tz_sekoliko_matiere_coeff VARCHAR(100) NOT NULL COLLATE utf8_general_ci, tz_sekoliko_matiere_nom VARCHAR(45) NOT NULL COLLATE utf8_general_ci, TZ-SEKOLIKO-PROF_id INT NOT NULL, INDEX fk_TZ-SEKOLIKO-MATIERE_TZ-SEKOLIKO-PROF1_idx (TZ-SEKOLIKO-PROF_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE TZ-SEKOLIKO-PROF (id INT AUTO_INCREMENT NOT NULL, tz_sekoliko_prof_nom VARCHAR(100) NOT NULL COLLATE utf8_general_ci, tz_sekoliko_prof_prenom VARCHAR(100) DEFAULT NULL COLLATE utf8_general_ci, tz_sekoliko_prof_fonction VARCHAR(100) NOT NULL COLLATE utf8_general_ci, tz_sekoliko_prof_date_debut DATETIME NOT NULL, tz_sekoliko_prof_contact VARCHAR(100) DEFAULT NULL COLLATE utf8_general_ci, tz_sekoliko_prof_date_fin DATETIME NOT NULL, tz_sekoliko_prof_date_is_fin TINYINT(1) NOT NULL, tz_sekoliko_prof_date_naissance DATETIME NOT NULL, tz_sekoliko_prof_sexe VARCHAR(45) NOT NULL COLLATE utf8_general_ci, TZ_SEKOLIKO_SESSION_id INT NOT NULL, INDEX fk_TZ-SEKOLIKO-PROF_TZ_SEKOLIKO_SESSION1_idx (TZ_SEKOLIKO_SESSION_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE TZ_SEKOLIKO_ADMIN (id INT AUTO_INCREMENT NOT NULL, tz_sekoliko_admin_nom VARCHAR(100) NOT NULL COLLATE utf8_general_ci, tz_sekoliko_admin_prenom VARCHAR(100) DEFAULT NULL COLLATE utf8_general_ci, tz_sekoliko_admin_fonction VARCHAR(100) NOT NULL COLLATE utf8_general_ci, tz_sekoliko_admin_date_debut DATETIME NOT NULL, tz_sekoliko_admin_contact VARCHAR(100) DEFAULT NULL COLLATE utf8_general_ci, tz_sekoliko_admin_date_fin DATETIME NOT NULL, tz_sekoliko_admin_date_is_fin TINYINT(1) NOT NULL, tz_sekoliko_admin_date_naissance DATETIME NOT NULL, tz_sekoliko_admin_sexe VARCHAR(45) NOT NULL COLLATE utf8_general_ci, TZ_SEKOLIKO_SESSION_id INT NOT NULL, INDEX fk_TZ_SEKOLIKO_ADMIN_TZ_SEKOLIKO_SESSION1_idx (TZ_SEKOLIKO_SESSION_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE TZ_SEKOLIKO_CLASSE (id INT NOT NULL, tz_sekoliko_class_nom VARCHAR(50) NOT NULL COLLATE utf8_general_ci, TZ_SEKOLIKO_SALLE_id INT NOT NULL, TZ_SEKOLIKO_SESSION_id INT NOT NULL, INDEX fk_TZ_SEKOLIKO_CLASSE_TZ_SEKOLIKO_SALLE1_idx (TZ_SEKOLIKO_SALLE_id), INDEX fk_TZ_SEKOLIKO_CLASSE_TZ_SEKOLIKO_SESSION1_idx (TZ_SEKOLIKO_SESSION_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE TZ_SEKOLIKO_ETABLISSEMENT (id INT AUTO_INCREMENT NOT NULL, tz_sekoly_nom VARCHAR(200) NOT NULL COLLATE utf8_general_ci, tz_sekoly_adresse VARCHAR(100) NOT NULL COLLATE utf8_general_ci, tz_sekoly_telephone VARCHAR(25) NOT NULL COLLATE utf8_general_ci, tz_sekoly_mail VARCHAR(50) DEFAULT NULL COLLATE utf8_general_ci, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE TZ_SEKOLIKO_ETUDIANT (id INT NOT NULL, tz_sekoliko_etudiant_nom VARCHAR(100) NOT NULL COLLATE utf8_general_ci, tz_sekoliko_etudiant_prenom VARCHAR(100) DEFAULT NULL COLLATE utf8_general_ci, tz_sekoliko_etudiant_contact VARCHAR(100) DEFAULT NULL COLLATE utf8_general_ci, tz_sekoliko_etudiant_sexe VARCHAR(100) NOT NULL COLLATE utf8_general_ci, tz_sekoliko_etudiant_date_naissance DATETIME NOT NULL, tz_sekoliko_etudiant_nom_copy1 VARCHAR(100) NOT NULL COLLATE utf8_general_ci, TZ_SEKOLIKO_CLASSE_id INT NOT NULL, TZ_SEKOLIKO_PAYEMENT_id INT NOT NULL, INDEX fk_TZ_SEKOLIKO_ETUDIANT_TZ_SEKOLIKO_CLASSE1_idx (TZ_SEKOLIKO_CLASSE_id), INDEX fk_TZ_SEKOLIKO_ETUDIANT_TZ_SEKOLIKO_PAYEMENT1_idx (TZ_SEKOLIKO_PAYEMENT_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE TZ_SEKOLIKO_NOTE (id INT NOT NULL, tz_sekoliko_note_valeur VARCHAR(100) NOT NULL COLLATE utf8_general_ci, TZ_SEKOLIKO_ETUDIANT_id INT NOT NULL, TZ-SEKOLIKO-MATIERE_id INT NOT NULL, INDEX fk_TZ_SEKOLIKO_NOTE_TZ_SEKOLIKO_ETUDIANT1_idx (TZ_SEKOLIKO_ETUDIANT_id), INDEX fk_TZ_SEKOLIKO_NOTE_TZ-SEKOLIKO-MATIERE1_idx (TZ-SEKOLIKO-MATIERE_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE TZ_SEKOLIKO_PAIEMENT (id INT NOT NULL, TZ-SEKOLIKO-PROF_id INT NOT NULL, TZ_SEKOLIKO_ADMIN_id INT NOT NULL, INDEX fk_TZ_SEKOLIKO_PAYEMENT_TZ-SEKOLIKO-PROF1_idx (TZ-SEKOLIKO-PROF_id), INDEX fk_TZ_SEKOLIKO_PAYEMENT_TZ_SEKOLIKO_ADMIN1_idx (TZ_SEKOLIKO_ADMIN_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE TZ_SEKOLIKO_SESSION (id INT NOT NULL, tz_sekoliko_session_debut VARCHAR(45) DEFAULT NULL COLLATE utf8_general_ci, tz_sekoliko_session_fin VARCHAR(45) DEFAULT NULL COLLATE utf8_general_ci, TZ_SEKOLIKO_ETABLISSEMENT_id INT NOT NULL, INDEX fk_TZ_SEKOLY_SESSION_TZ_SEKOLIKO_ETABLISSEMENT1_idx (TZ_SEKOLIKO_ETABLISSEMENT_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE MGMT_FONCTION ADD CONSTRAINT fk_MGMT_FONCTION_MGMT_POLE1 FOREIGN KEY (MGMT_POLE_id) REFERENCES MGMT_POLE (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE MGMT_PROJET_LOT ADD CONSTRAINT fk_MGMT_PROJET_LOT_MGMT_PROJET1 FOREIGN KEY (MGMT_PROJET_id) REFERENCES MGMT_PROJET (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE MGMT_PROJET_LOT ADD CONSTRAINT fk_MGMT_PROJET_LOT_MGMT_PROJET_LOT_STATUT1 FOREIGN KEY (MGMT_PROJET_LOT_STATUT_id) REFERENCES MGMT_PROJET_LOT_STATUT (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE MGMT_PROJET_LOT_EQUIPE ADD CONSTRAINT fk_MGMT_PROJET_LOT_EQUIPE_MGMT_PROJET_LOT1 FOREIGN KEY (MGMT_PROJET_LOT_id) REFERENCES MGMT_PROJET_LOT (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE MGMT_PROJET_LOT_EQUIPE ADD CONSTRAINT fk_MGMT_PROJET_LOT_EQUIPE_MGMT_USER1 FOREIGN KEY (MGMT_USER_id) REFERENCES TZ_SEKOLIKO_ETABLISSEMENT (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE MGMT_PROJET_LOT_TACHE ADD CONSTRAINT fk_MGMT_PROJET_LOT_TACHE_MGMT_PROJET_LOT1 FOREIGN KEY (MGMT_PROJET_LOT_id) REFERENCES MGMT_PROJET_LOT (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE MGMT_PROJET_LOT_TACHE ADD CONSTRAINT fk_MGMT_PROJET_LOT_TACHE_MGMT_PROJET_LOT_TACHE1 FOREIGN KEY (MGMT_PROJET_LOT_TACHE_id) REFERENCES MGMT_PROJET_LOT_TACHE (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE MGMT_PROJET_LOT_TACHE ADD CONSTRAINT fk_MGMT_PROJET_LOT_TACHE_MGMT_PROJET_LOT_TACHE_STATUT1 FOREIGN KEY (MGMT_PROJET_LOT_TACHE_STATUT_id) REFERENCES MGMT_PROJET_LOT_TACHE_STATUT (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE MGMT_PROJET_LOT_TACHE ADD CONSTRAINT fk_MGMT_PROJET_LOT_TACHE_MGMT_USER1 FOREIGN KEY (MGMT_USER_id) REFERENCES TZ_SEKOLIKO_ETABLISSEMENT (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE MGMT_USER_FONCTION ADD CONSTRAINT fk_MGMT_USER_FONCTION_MGMT_FONCTION1 FOREIGN KEY (MGMT_FONCTION_id) REFERENCES MGMT_FONCTION (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE MGMT_USER_FONCTION ADD CONSTRAINT fk_MGMT_USER_FONCTION_MGMT_USER1 FOREIGN KEY (MGMT_USER_id) REFERENCES TZ_SEKOLIKO_ETABLISSEMENT (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE TZ-SEKOLIKO-MATIERE ADD CONSTRAINT fk_TZ-SEKOLIKO-MATIERE_TZ-SEKOLIKO-PROF1 FOREIGN KEY (TZ-SEKOLIKO-PROF_id) REFERENCES TZ-SEKOLIKO-PROF (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE TZ-SEKOLIKO-PROF ADD CONSTRAINT fk_TZ-SEKOLIKO-PROF_TZ_SEKOLIKO_SESSION1 FOREIGN KEY (TZ_SEKOLIKO_SESSION_id) REFERENCES TZ_SEKOLIKO_SESSION (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE TZ_SEKOLIKO_ADMIN ADD CONSTRAINT fk_TZ_SEKOLIKO_ADMIN_TZ_SEKOLIKO_SESSION1 FOREIGN KEY (TZ_SEKOLIKO_SESSION_id) REFERENCES TZ_SEKOLIKO_SESSION (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE TZ_SEKOLIKO_CLASSE ADD CONSTRAINT fk_TZ_SEKOLIKO_CLASSE_TZ_SEKOLIKO_SALLE1 FOREIGN KEY (TZ_SEKOLIKO_SALLE_id) REFERENCES TZ_SEKOLIKO_SALLE (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE TZ_SEKOLIKO_CLASSE ADD CONSTRAINT fk_TZ_SEKOLIKO_CLASSE_TZ_SEKOLIKO_SESSION1 FOREIGN KEY (TZ_SEKOLIKO_SESSION_id) REFERENCES TZ_SEKOLIKO_SESSION (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE TZ_SEKOLIKO_ETUDIANT ADD CONSTRAINT fk_TZ_SEKOLIKO_ETUDIANT_TZ_SEKOLIKO_CLASSE1 FOREIGN KEY (TZ_SEKOLIKO_CLASSE_id) REFERENCES TZ_SEKOLIKO_CLASSE (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE TZ_SEKOLIKO_ETUDIANT ADD CONSTRAINT fk_TZ_SEKOLIKO_ETUDIANT_TZ_SEKOLIKO_PAYEMENT1 FOREIGN KEY (TZ_SEKOLIKO_PAYEMENT_id) REFERENCES TZ_SEKOLIKO_PAIEMENT (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE TZ_SEKOLIKO_NOTE ADD CONSTRAINT fk_TZ_SEKOLIKO_NOTE_TZ-SEKOLIKO-MATIERE1 FOREIGN KEY (TZ-SEKOLIKO-MATIERE_id) REFERENCES TZ-SEKOLIKO-MATIERE (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE TZ_SEKOLIKO_NOTE ADD CONSTRAINT fk_TZ_SEKOLIKO_NOTE_TZ_SEKOLIKO_ETUDIANT1 FOREIGN KEY (TZ_SEKOLIKO_ETUDIANT_id) REFERENCES TZ_SEKOLIKO_ETUDIANT (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE TZ_SEKOLIKO_PAIEMENT ADD CONSTRAINT fk_TZ_SEKOLIKO_PAYEMENT_TZ-SEKOLIKO-PROF1 FOREIGN KEY (TZ-SEKOLIKO-PROF_id) REFERENCES TZ-SEKOLIKO-PROF (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE TZ_SEKOLIKO_PAIEMENT ADD CONSTRAINT fk_TZ_SEKOLIKO_PAYEMENT_TZ_SEKOLIKO_ADMIN1 FOREIGN KEY (TZ_SEKOLIKO_ADMIN_id) REFERENCES TZ_SEKOLIKO_ADMIN (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE TZ_SEKOLIKO_SESSION ADD CONSTRAINT fk_TZ_SEKOLY_SESSION_TZ_SEKOLIKO_ETABLISSEMENT1 FOREIGN KEY (TZ_SEKOLIKO_ETABLISSEMENT_id) REFERENCES TZ_SEKOLIKO_ETABLISSEMENT (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('DROP TABLE sekoliko_horaire');
        $this->addSql('DROP TABLE sekoliko_jour_ferie');
        $this->addSql('DROP TABLE sekoliko_role');
        $this->addSql('DROP TABLE sekoliko_user');
        $this->addSql('ALTER TABLE tz_sekoliko_edt ADD TZ-SEKOLIKO-MATIERE_id INT NOT NULL, ADD TZ-SEKOLIKO-PROF_id INT NOT NULL, ADD TZ_SEKOLIKO_SALLE_id INT NOT NULL, CHANGE id id INT NOT NULL, CHANGE tz_sekoliko_edt_heure_debut tz_sekoliko_edt_heure_debut DATETIME NOT NULL, CHANGE tz_sekoliko_edt_heure_fin tz_sekoliko_edt_heure_fin DATETIME NOT NULL');
        $this->addSql('ALTER TABLE tz_sekoliko_edt ADD CONSTRAINT fk_TZ_SEKOLIKO_EDT_TZ-SEKOLIKO-MATIERE1 FOREIGN KEY (TZ-SEKOLIKO-MATIERE_id) REFERENCES TZ-SEKOLIKO-MATIERE (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE tz_sekoliko_edt ADD CONSTRAINT fk_TZ_SEKOLIKO_EDT_TZ-SEKOLIKO-PROF1 FOREIGN KEY (TZ-SEKOLIKO-PROF_id) REFERENCES TZ-SEKOLIKO-PROF (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE tz_sekoliko_edt ADD CONSTRAINT fk_TZ_SEKOLIKO_EDT_TZ_SEKOLIKO_SALLE1 FOREIGN KEY (TZ_SEKOLIKO_SALLE_id) REFERENCES TZ_SEKOLIKO_SALLE (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('CREATE INDEX fk_TZ_SEKOLIKO_EDT_TZ-SEKOLIKO-MATIERE1_idx ON tz_sekoliko_edt (TZ-SEKOLIKO-MATIERE_id)');
        $this->addSql('CREATE INDEX fk_TZ_SEKOLIKO_EDT_TZ-SEKOLIKO-PROF1_idx ON tz_sekoliko_edt (TZ-SEKOLIKO-PROF_id)');
        $this->addSql('CREATE INDEX fk_TZ_SEKOLIKO_EDT_TZ_SEKOLIKO_SALLE1_idx ON tz_sekoliko_edt (TZ_SEKOLIKO_SALLE_id)');
        $this->addSql('ALTER TABLE tz_sekoliko_salle CHANGE id id INT NOT NULL');
    }
}
